version: '3.3'
services:
  mongo:
    container_name: fanginterview-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ottawa101#1
    volumes:
      - ./data:/data/db #the data should not be deleted when redeploy, so use a folder in root directory
    ports:
      - 20091:27017

  mongo-express:
    container_name: fanginterview-mongodb-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 20092:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ottawa101#1
    links:
      - mongo
  
  fanginterview-prod:
    container_name: fanginterview-backend_inst
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "80:3000"
    environment:
      TZ: "America/Toronto"
      NEXTAUTH_URL: "http://crackingdatascienceinterview.com"
    depends_on:
      - mongo
    links:
      - mongo
