version: '3.3'
services:
  mongo:
    container_name: fanginterview-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ottawa101#1
    volumes:
      - ./data:/data/db #the data should not be deleted when redeploy, so use a folder in root directory
    ports:
      - 20091:27017
    networks: 
      - mongo-compose-network
  mongo-express:
    container_name: fanginterview-mongodb-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 20092:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ottawa101#1
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ottawa101#1
    networks: 
      - mongo-compose-network
    links:
      - mongo
    depends_on:
      - mongo
  
networks:
  mongo-compose-network:
    driver: bridge
