import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { gql } from "@apollo/client";
import client from "../apollo-client";
import { GetStaticProps} from 'next'
import Button from '@mui/material/Button';
import Link from 'next/link'

export const getStaticProps: GetStaticProps = async(context) =>{
  const { data } = await client.query({
    query: gql`
      query Query {
        hello
      }
    `,
  });
  
  return {
    props: {
      data: data
    },
 };
}

const Home: NextPage<{data: any}> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Cracking Data Science Interview
        </h1>
       <h2>
        
        <Link href="/all-articles">
          <a>Get started to become a Data Scientist!</a>
        </Link>
       </h2>
        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}
        <input></input>

        <p>
          {JSON.stringify(props.data)}
        </p>
      </main>
        <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' crackingdatascienceinterview.com'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
